# Generated by Django 6.0.4 on 2026-04-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
